const help = [
  {
    id: 1,
    title: "Order Processing",
    category: "buying",
    body: "Orders are processed and shipped on business days only (Sunday through Thursday, excluding Holidays).\nOrders placed on Holidays or Weekend Days will be processed the following business day.",
  },
  {
    id: 2,
    title: "Order Status",
    category: "buying",
    body: "You can access your order status and history by signing in and viewing it in your account. \nOrder status is updated by sellers only.",
  },
  {
    id: 3,
    title: "Order Cancellations",
    category: "buying",
    body: "If you would like to cancel an online order after it has been placed, please do it at your earliest convenience through the order cancellation tab. Once an order is processing, we regret that it cannot be changed or canceled.\nFeel free to contact us by phone in case you encounter any issues during your cancellation. We will do our best to accommodate your request.",
  },
  {
    id: 4,
    title: "Maximum Purchase Policy",
    category: "buying",
    body: "We must limit orders to ten (10) of any single item. Orders exceeding these limits are subject to cancellation. If you have any questions Contact Us and we will be happy to assist.",
  },
  {
    id: 5,
    title: "Payment Options",
    category: "buying",
    body: "We accept two payment methods:\nPayment on delivery: physical money is exchanged for the item you ordered upon receiving it. Customers must keep in mind that the price they were shown during checkout is non negotiable at this step.\nPayment through website credit: the total amount of your order will be deducted from your credit balance if the current balance is enough to cover it. See the section about site credit to learn more about it.",
  },
  {
    id: 6,
    title: "Site Credit",
    category: "buying",
    body: "You can purchase site credit upwards of 1000 DZD and no more than 50000 DZD by wiring the desired amount through your local bank to this account. A site administrator will add that amount to your current balance at the shortest possible notice. Once it is added, it cannot be refunded. Please Contact Us for any other inquiries regarding site credit.",
  },
  {
    id: 7,
    title: "Promotional Offer Code",
    category: "buying",
    body: "Simply enter your offer code in the text box marked “Offer Code” on the Billing page during the Checkout process. When an offer code is accepted, it will be displayed on the “Order Review” page. Please Note: Offer codes are case sensitive and should be entered exactly as they appear. Only one offer code may be used per online order.",
  },
  {
    id: 8,
    title: "Opening a Store",
    category: "selling",
    body: "To open your own Magaza store, click here. \n\nMagaza relies entirely on its sellers and their convenience is important to us. Once you fill the online form for opening a store, a site administrator will contact you to confirm the operation and take additional information.\n\nFor a store to show up on the stores page, it has to have a valid name, description, profile and banner photos as well as a contact section. Additionally, at least one product validated through our administrators is needed for your store to become operational.",
  },
  {
    id: 9,
    title: "Selling Products",
    category: "selling",
    body: "The quality of our products is our top priority, therefore sellers are expected to take real and clear photos of their products as well as provide enough information about them, all of which will be checked and validated by our administrators.\nIn case a product submission gets rejected, you can contact us for additional information.",
  },
  {
    id: 10,
    title: "Handling Customer Orders",
    category: "selling",
    body: "Store owners and managers are expected to process and ship orders within a couple business days of receiving them. Failure to do so on multiple occasions may lead to a store suspension. Additionally, physical returns and on hand payment will be handled by your store staff.",
  },
  {
    id: 11,
    title: "Reviews and Questions",
    category: "selling",
    body: "You can find your product reviews and customer’s inquiries here.\nWhile reviews cannot be deleted, they can be reported in case of usage of inappropriate language. As for questions, they will not show up on the product page until you send an answer.",
  },
  {
    id: 12,
    title: "Online Store Staff",
    category: "selling",
    body: "To make your experience easier, you can add up to 3 store managers to help you handle orders and answer questions. They will first have to be approved by our administrators. \n*Magaza does not handle paying their wages.",
  },
  {
    id: 13,
    title: "Store Credit",
    category: "selling",
    body: "Any products sold to customers who have chosen the online payment method will be deducted from your online inventory and their price added to your store credit. At the end of every month, the total will be sent to you via the bank account you submitted through the store sign up form.\nAny real life transactions such as on hand delivery payment and shipping costs is not handled by Magaza, however, the total for on hand payment will be shown on your store dashboard to give you accurate statistics of your sales.",
  },
  {
    id: 14,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 15,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 16,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 17,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 18,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 19,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 20,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 21,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 22,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 23,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 24,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 25,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 26,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 27,
    title: "",
    category: "",
    body: "",
  },
  {
    id: 28,
    title: "",
    category: "",
    body: "",
  },
];

module.exports = help;
